import path from 'path';

const port = process.env.PORT || 4000;

// Determine the server URL used in Swagger UI. When deployed on Vercel,
// VERCEL_URL is set to <project>.vercel.app. Prefer an explicit PUBLIC_URL
// if provided (useful for custom domains). Fallback to localhost for dev.
//const publicUrl = 'https://backend-ruddy-tau-76.vercel.app/docs';

export const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'TCI API 🏨',
      version: '1.0.0',
      description: 'API documentation for TCI Platform',
    },
    // Use a relative server URL so Swagger UI uses the current origin.
    // This avoids localhost being embedded at build time when deployed to Vercel.
    // servers: [{ url: '/' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
      // --- MOVED SCHEMAS INSIDE COMPONENTS ---
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'STU-2025-1234' },
            name: { type: 'string', example: 'John Doe' },
            email: { type: 'string', example: 'john@example.com' },
            role: {
              type: 'string',
              enum: ['ADMIN', 'STUDENT'],
              example: 'STUDENT',
            },
          },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string' },
            password: { type: 'string' },
          },
        },
        Product: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            createdById: { type: 'integer', example: 1 },
            updatedById: { type: 'integer', nullable: true, example: 2 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        CreateProductRequest: {
          type: 'object',
          required: ['name', 'slug', 'sku', 'price', 'categoryId'],
          properties: {
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
          },
        },
        UpdateProductRequest: {
          type: 'object',
          properties: {
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
          },
        },
        ProductVariant: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            productId: { type: 'integer', example: 1 },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
        CreateProductVariantRequest: {
          type: 'object',
          required: ['name', 'productId'],
          properties: {
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            productId: { type: 'integer', example: 1 },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
        UpdateProductVariantRequest: {
          type: 'object',
          properties: {
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: [
    './src/routes/*.ts',
    './src/routes/*.js',
    './dist/routes/*.js',
    './api/*.ts', // if vercel uses api folder
  ],
};
